[package]
name = "swayped"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input = "0.7"
libc = "0.2"
log = "0.4"
nix = "0.23"
swayipc = "3.0"
syslog = "6.0"
